<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerImCrk5u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerImCrk5u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerImCrk5u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerImCrk5u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerImCrk5u\App_KernelDevDebugContainer([
    'container.build_hash' => 'ImCrk5u',
    'container.build_id' => '05ff802c',
    'container.build_time' => 1730894639,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerImCrk5u');
